{
  "repositories": [
    {
      "name": "raisin_master",
      "path": "..",
      "remote": "git@github.com:raionrobotics/raisin_master.git",
      "branch": "main",
      "commit": "e52cf02f056b570a407ef95cb131cb9363ec4e3d"
    },
    {
      "name": "raipal_controller",
      "path": "raipal_controller",
      "remote": "git@github.com:railabatkaist/raipal_controller.git",
      "branch": "feat/trajectory",
      "commit": "21a46b31af579ec63345700fef0cd35d47c2d3d4"
    },
    {
      "name": "raisin",
      "path": "raisin",
      "remote": "git@github.com:raionrobotics/raisin.git",
      "branch": "main",
      "commit": "1cc126a6e065b859af2f6dc770cf5dfd9ae50a82"
    },
    {
      "name": "raisin_gui",
      "path": "raisin_gui",
      "remote": "git@github.com:raionrobotics/raisin_gui.git",
      "branch": "main",
      "commit": "d166081d9dda255cac5807abac4333a51cb152a9"
    },
    {
      "name": "raisin_plugin",
      "path": "raisin_plugin",
      "remote": "git@github.com:raionrobotics/raisin_plugin.git",
      "branch": "main",
      "commit": "6d5aebe0053adc6b441b72fe31548d447f824f64"
    },
    {
      "name": "raisin_raipal",
      "path": "raisin_raipal",
      "remote": "git@github.com:railabatkaist/raisin_raipal.git",
      "branch": "main",
      "commit": "c8e776f8fbf59ae712787aa8e35e65e6129d6214"
    },
    {
      "name": "raisin_robot_packages",
      "path": "raisin_robot_packages",
      "remote": "git@github.com:raionrobotics/raisin_robot_packages.git",
      "branch": "main",
      "commit": "56ec9f2173cdece95c0db6e8478cf1ef2090538c"
    }
  ]
}
