{
  "repositories": [
    {
      "name": "raisin_master",
      "path": "..",
      "remote": "git@github.com:raionrobotics/raisin_master.git",
      "branch": "main",
      "commit": "e52cf02f056b570a407ef95cb131cb9363ec4e3d"
    },
    {
      "name": "raibo_controller",
      "path": "raibo_controller",
      "remote": "git@github.com:raionrobotics/raibo_controller.git",
      "branch": "main",
      "commit": "14e6c18f035e2de29f65d7403a5234373fa570b7"
    },
    {
      "name": "raipal_controller",
      "path": "raipal_controller",
      "remote": "git@github.com:railabatkaist/raipal_controller.git",
      "branch": "feat/ik-teleop",
      "commit": "7c2c5a6955d126b554f431402cfd9cc12c42e34d"
    },
    {
      "name": "raisin",
      "path": "raisin",
      "remote": "git@github.com:raionrobotics/raisin.git",
      "branch": "main",
      "commit": "1cc126a6e065b859af2f6dc770cf5dfd9ae50a82"
    },
    {
      "name": "raisin_gui",
      "path": "raisin_gui",
      "remote": "git@github.com:raionrobotics/raisin_gui.git",
      "branch": "feat/fixed_base",
      "commit": "b4e193ba8f015045b82a77faa08399457cb475b6"
    },
    {
      "name": "raisin_plugin",
      "path": "raisin_plugin",
      "remote": "git@github.com:raionrobotics/raisin_plugin.git",
      "branch": "main",
      "commit": "6d5aebe0053adc6b441b72fe31548d447f824f64"
    },
    {
      "name": "raisin_raibo2",
      "path": "raisin_raibo2",
      "remote": "git@github.com:raionrobotics/raisin_raibo2.git",
      "branch": "main",
      "commit": "100006169be18ab7434b49b44e0d250f5e10d0be"
    },
    {
      "name": "raisin_raipal",
      "path": "raisin_raipal",
      "remote": "git@github.com:railabatkaist/raisin_raipal.git",
      "branch": "main",
      "commit": "0bb86d9f2b1cd8e7e80ff8398d6523c8ecab8971"
    },
    {
      "name": "raisin_robot_packages",
      "path": "raisin_robot_packages",
      "remote": "git@github.com:raionrobotics/raisin_robot_packages.git",
      "branch": "main",
      "commit": "56ec9f2173cdece95c0db6e8478cf1ef2090538c"
    }
  ]
}
