{
  "repositories": [
    {
      "name": "raisin_master",
      "path": "..",
      "remote": "git@github.com:raionrobotics/raisin_master.git",
      "branch": "main",
      "commit": "e52cf02f056b570a407ef95cb131cb9363ec4e3d"
    },
    {
      "name": "raipal_controller",
      "path": "raipal_controller",
      "remote": "git@github.com:railabatkaist/raipal_controller.git",
      "branch": "feat/ik-teleop",
      "commit": "7c2c5a6955d126b554f431402cfd9cc12c42e34d"
    },
    {
      "name": "raisin",
      "path": "raisin",
      "remote": "git@github.com:raionrobotics/raisin.git",
      "branch": "main",
      "commit": "1cc126a6e065b859af2f6dc770cf5dfd9ae50a82"
    },
    {
      "name": "raisin_gui",
      "path": "raisin_gui",
      "remote": "git@github.com:raionrobotics/raisin_gui.git",
      "branch": "feat/fixed_base",
      "commit": "8bbd178d6b6792c6cf039fddf83d02b640c4ab35"
    },
    {
      "name": "raisin_plugin",
      "path": "raisin_plugin",
      "remote": "git@github.com:raionrobotics/raisin_plugin.git",
      "branch": "main",
      "commit": "6d5aebe0053adc6b441b72fe31548d447f824f64"
    },
    {
      "name": "raisin_raipal",
      "path": "raisin_raipal",
      "remote": "git@github.com:iamchoking/raisin_raipal.git",
      "branch": "feat/get-ready",
      "commit": "a5047877b24e3ac8924878ecde459d48bb453200"
    },
    {
      "name": "raisin_robot_packages",
      "path": "raisin_robot_packages",
      "remote": "git@github.com:raionrobotics/raisin_robot_packages.git",
      "branch": "main",
      "commit": "56ec9f2173cdece95c0db6e8478cf1ef2090538c"
    }
  ]
}
