{
  "repositories": [
    {
      "name": "raisin_master",
      "path": "..",
      "remote": "git@github.com:raionrobotics/raisin_master.git",
      "branch": "main",
      "commit": "1cb603863bb4eb8bbc1c2afd18790a90117d3936"
    },
    {
      "name": "raipal_controller",
      "path": "raipal_controller",
      "remote": "git@github.com:railabatkaist/raipal_controller.git",
      "branch": "feat/dual-arms",
      "commit": "e07228f30597b471579502403e0b97cef55a4363"
    },
    {
      "name": "raisin",
      "path": "raisin",
      "remote": "git@github.com:raionrobotics/raisin.git",
      "branch": "main",
      "commit": "5e2ca6126ccb5b3aa49ac34c545a4fba85d7ffec"
    },
    {
      "name": "raisin_gui",
      "path": "raisin_gui",
      "remote": "git@github.com:raionrobotics/raisin_gui.git",
      "branch": "chore/config-path",
      "commit": "07820b7fc98697c0081db3bf30796d167d3c6fa1"
    },
    {
      "name": "raisin_plugin",
      "path": "raisin_plugin",
      "remote": "git@github.com:raionrobotics/raisin_plugin.git",
      "branch": "main",
      "commit": "57af14182bd79acb50d7bd3a666da27b4e57f871"
    },
    {
      "name": "raisin_raipal",
      "path": "raisin_raipal",
      "remote": "git@github.com:railabatkaist/raisin_raipal.git",
      "branch": "feat/dual-arms",
      "commit": "b16bf384092f4924465606ef8c3cfc4c4a5d4d1f"
    },
    {
      "name": "raisin_robot_packages",
      "path": "raisin_robot_packages",
      "remote": "git@github.com:raionrobotics/raisin_robot_packages.git",
      "branch": "main",
      "commit": "7c6c74e893ffa6c5290be36c423b8081878d38a6"
    },
    {
      "name": "raisin_third_party_gui",
      "path": "raisin_third_party_gui",
      "remote": "git@github.com:raionrobotics/raisin_third_party_gui.git",
      "branch": "main",
      "commit": "c2912ab0f1a2cdf110daeb068bcc2413c705fa51"
    }
  ]
}
